# Site settings
title: NDPF-Portfolio
email: you@example.com
description: >
  A simple, whitespace, helvetica based portfolio theme.
baseurl: /portfolio
url: https://nordicpuff.github.io
twitter_username: twitter_username
github_username:  github_username

# Build settings
markdown: kramdown

highlighter: rouge

# Pagination
paginate: 15
paginate_path: "/about/page:num/"


collections:
  projects:
    output: true
    permalink: /projects/:path/
  updates:
    output: true
    permalink: /updates/:path/
